<?php
_("Top Bottom Settings");
_("Value format");
_("Interval");
_("Display resources with this status");
_("Display resources with this state");
_("Display resources with these status types");
_("Host severities");
_("Service severities");
_("Enable Open Tickets");
_("Rule (ticket provider)");
_("Display resources");
_("Hide services with Down host");
_("hide services with Unreachable host");
_("Problem (Down/Critical)");
_("Warning");
_("Pending");
_("Success (OK/Up)");
_("Undefined (Unreachable/Unknown)");
_("Unhandled");
_("Acknowledged");
_("In downtime");
_("Hard");
_("Soft");
_("All resources");
_("Resources linked to a ticket");
_("Resources with no ticket");
_("Select host severities");
_("Select service severities");
_("Select rule (ticket provider)");
_("Donut chart");
_("Pie chart");
_("Horizontal bar chart");
_("Vertical bar chart");
_("Display resources with this type");
_("Display resources with this unit");
_("Show value on chart");
_("Show legend");
_("Host");
_("Service");
_("Percentage");
_("Number");
_("Legend");
_("Display with this view");
_("Sort by");
_("Standard");
_("Condensed");
_("Status");
_("Name");
_("Text");
_("Gauge");
_("Bar");
_("Select field");
_("Radio");
_("Group");
_("Sub input 1");
_("Sub input 2");
_("Sub input 3");
_("Group name");
_("Option 1");
_("Option 2");
_("Button 1");
_("Button 2");
_("Button 3");
_("Button 4");
_("sub1");
_("sub2");
_("Radio 1");
_("Radio 2");
_("sub3");
_("Line");
_("Stacked bar");
_("Curve type");
_("Display curve points");
_("Line width");
_("Show area");
_("Fill opacity");
_("Line style");
_("Dash width");
_("Space");
_("Orientation");
_("Bar radius");
_("Bar background opacity");
_("Show axis border");
_("Y-axis tick label rotation");
_("Zero-centered");
_("Show grid lines");
_("Grid lines type");
_("Scale");
_("Display mode");
_("Position");
_("Tooltip display");
_("Value sorting");
_("Graph style");
_("Axis");
_("Tooltip");
_("Linear");
_("Natural");
_("Step");
_("Auto");
_("Custom");
_("lineWidth");
_("Show");
_("Hide");
_("areaOpacity");
_("Solid");
_("Dashed");
_("Dotted");
_("dashLength");
_("dashOffset");
_("dotOffset");
_("Horizontal");
_("Vertical");
_("gridLinesType");
_("Both");
_("Logarithmic");
_("scaleLogarithmicBase");
_("Base 2");
_("Base 10");
_("legendDisplayMode");
_("Grid");
_("List");
_("legendPlacement");
_("Left");
_("Bottom");
_("Right");
_("All");
_("Single");
_("Hidden");
_("By name");
_("Ascending");
_("Descending");
_("The Auto value corresponds to the value defined in the Curves configuration in Centreon.");
_("Display the diagram with this status");
_("Link types");
_("Problem (Critical)");
_("Success (OK)");
_("Curve");
_("Generic text");
?>
